# Generated by Django 2.2.3 on 2019-07-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('specialaddress', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('menu', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('hashtag', models.CharField(max_length=200)),
            ],
        ),
    ]
