# Generated by Django 2.2.3 on 2019-07-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.CharField(choices=[('한식', '한식'), ('중식', '중식'), ('일식', '일식'), ('양식', '양식'), ('디저트', '디저트')], default=50, max_length=20),
            preserve_default=False,
        ),
    ]
