# Generated by Django 2.2.3 on 2019-07-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='priceChar',
            field=models.CharField(default=50, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.IntegerField(),
        ),
    ]
